<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\empresas;

class EmpresasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('Empresas')->insert(array(
            array('id' => '1','rut' => '8276861-0','name' => 'Hermann Berkhoff de prueba','name_corto' => 'HEBF','item_id5' => '27','tipo_empresa' => 'Persona Natural','actividad' => NULL,'direccion' => NULL,'region_id' => '9','region' => 'Araucania','comuna_id' => '227','comuna' => 'TEMUCO','ciudad_id' => '1','ciudad' => 'Villarrica','codpostal' => '0','email' => 'Hermann@Berkhoff.cl','fono' => NULL,'feinicio' => '2019-02-26','tipo_tributacion' => 'Renta Presunta','item_id6' => '59','segmento' => 'Personas','item_id10' => '61','codigo' => '741200','giro' => 'ACTIVIDADES DE CONTABILIDAD, TENEDUR0A DE LIBROS Y AUDITOR0A; ASESORAMIENTOS TRIBUTARIOS','logo' => 'default_logo.jpg','capital' => '0','notario' => NULL,'fenotario' => '2019-01-03','repertorio' => NULL,'nro_edicion' => NULL,'fediario' => '2019-02-06','reg_comercio' => NULL,'notas' => NULL,'deleted_at' => '2020-09-04 10:30:46','created_at' => '2018-05-02 18:59:51','updated_at' => '2020-09-04 10:30:46'),
            array('id' => '2','rut' => '76066491-K','name' => 'Asesorias y Servicios ASA Ltda','name_corto' => 'ASA','item_id5' => '28','tipo_empresa' => 'Soc. de Responsabilidad Limitada','actividad' => 'Asesorias y servicios integrales a Empresas en Contabilidad tributaria laboral y computacional','direccion' => 'D. Portales N� 1383','region_id' => '9','region' => 'Araucania','comuna_id' => '227','comuna' => 'TEMUCO','ciudad_id' => '2','ciudad' => 'Temuco','codpostal' => '47900954','email' => 'asesorias@asatemuco.cl','fono' => '45-2994321','feinicio' => '2009-08-18','tipo_tributacion' => 'Renta Presunta','item_id6' => '59','segmento' => 'Personas','item_id10' => '61','codigo' => '741400','giro' => 'ACTIVIDADES DE ASESORAMIENTO EMPRESARIAL Y EN MATERIA DE GESTION','logo' => '2_logo1556833035.JPG','capital' => '10000000','notario' => 'Alarcon','fenotario' => '2009-06-30','repertorio' => '2706-09','nro_edicion' => NULL,'fediario' => '2009-07-09','reg_comercio' => '668 vta. n� 638','notas' => NULL,'deleted_at' => NULL,'created_at' => '2018-05-02 19:05:35','updated_at' => '2020-09-04 10:27:12'),
            array('id' => '3','rut' => '76104329-3','name' => 'Industrial y Comercial Cente','name_corto' => 'Cente','item_id5' => '28','tipo_empresa' => 'Soc. de Responsabilidad Limitada','actividad' => 'Fabrica de Productos plasticos','direccion' => NULL,'region_id' => '9','region' => 'Araucania','comuna_id' => '227','comuna' => 'TEMUCO','ciudad_id' => '2','ciudad' => 'Temuco','codpostal' => '0','email' => 'industrial@cente.cl','fono' => '45-2923770','feinicio' => '2010-07-13','tipo_tributacion' => 'Art. 14 A','item_id6' => '0','segmento' => 'Mediana','item_id10' => '0','codigo' => '252090','giro' => 'FABRICACI0N DE OTROS ART0CULOS DE PL0STICO','logo' => 'logo','capital' => '6000000','notario' => NULL,'fenotario' => NULL,'repertorio' => NULL,'nro_edicion' => NULL,'fediario' => NULL,'reg_comercio' => NULL,'notas' => '<p>Observacion DJ 1923&nbsp;\\r\\n\\r\\nDE ACUERDO A LA INFORMACI&Oacute;N QUE TIENE EL SII, SU DECLARACI&Oacute;N JURADA FORM. N&deg; 1923, PRESENTA INCONSISTENCIAS EN LO REFERENTE AL RUT DEL SOCIO O COMUNERO INFORMADO. Renta AT 2019 Declaraci&oacute;n con inconsistencias. PPM traspasados a socios.</p>\\r\\n\\r\\n<p>Tu declaraci&oacute;n presenta inconsistencias con respecto a la informaci&oacute;n que el SII tiene en sus sistemas y la proporcionada por ti y/o por los agentes retenedores o informantes, por lo tanto se ha impugnado tu declaraci&oacute;n. Para mayor informaci&oacute;n consulte el estado de tu declaraci&oacute;n a partir del 21 de mayo del presente a&ntilde;o .</p>','deleted_at' => NULL,'created_at' => '2018-05-23 21:59:52','updated_at' => '2019-05-16 15:48:16'),
            array('id' => '4','rut' => '76310360-9','name' => 'Olleta Caza y Pesca S.A','name_corto' => 'C y P S.A.','item_id5' => '29','tipo_empresa' => 'Soc. Anonima Cerrada','actividad' => 'VENTA DE ART�CULOS CAZA Y PESCA,DEPORTES','direccion' => 'ARTURO PRAT #439 DEPTO. #D','region_id' => '9','region' => 'Araucania','comuna_id' => '227','comuna' => 'TEMUCO','ciudad_id' => '2','ciudad' => 'Temuco','codpostal' => '0','email' => 'berkhoff@asatemuco.cl','fono' => NULL,'feinicio' => '2005-06-21','tipo_tributacion' => 'Art. 14 B','item_id6' => '0','segmento' => 'Mediana','item_id10' => '0','codigo' => '476301','giro' => 'VENTA AL POR MENOR DE ART�CULOS DE CAZA Y PESCA EN COMERCIOS ESPECIALIZADOS','logo' => 'default_logo.jpg','capital' => '123182','notario' => NULL,'fenotario' => '2019-03-15','repertorio' => NULL,'nro_edicion' => NULL,'fediario' => '2019-03-15','reg_comercio' => NULL,'notas' => '<p>Renta AT 2019</p>\\r\\n\\r\\n<p>Su devoluci&oacute;n solicitada por $4.520.835 fue autorizada.</p>','deleted_at' => NULL,'created_at' => '2019-03-15 13:44:13','updated_at' => '2020-08-31 16:24:26'),
            array('id' => '5','rut' => '77163910-0','name' => 'Comercial y Proveedores del Sur Ltda.','name_corto' => 'Provesur','item_id5' => '28','tipo_empresa' => 'Soc. de Responsabilidad Limitada','actividad' => 'Compraventa de art�culos de ferreteria, y maderas','direccion' => 'Guido Beck de Ramberga #882','region_id' => '9','region' => 'Araucania','comuna_id' => '227','comuna' => 'TEMUCO','ciudad_id' => '2','ciudad' => 'Temuco','codpostal' => '0','email' => 'berkhoff@asatemuco.com','fono' => NULL,'feinicio' => '1998-07-01','tipo_tributacion' => 'Art. 14 B','item_id6' => '0','segmento' => 'Grande','item_id10' => '0','codigo' => '475201','giro' => 'VENTA AL POR MENOR DE ART�CULOS DE FERRETER�A Y MATERIALES DE CONSTRUCCI�N&nbsp;','logo' => 'default_logo.jpg','capital' => '0','notario' => NULL,'fenotario' => '2019-03-18','repertorio' => NULL,'nro_edicion' => NULL,'fediario' => '2019-03-18','reg_comercio' => NULL,'notas' => '<p>Renta AT 2019&nbsp;Declaraci&oacute;n con inconsistencias.</p>','deleted_at' => NULL,'created_at' => '2019-03-18 14:14:52','updated_at' => '2019-05-16 15:59:43'),
            array('id' => '6','rut' => '76051775-5','name' => 'Maquinarias y Construciones la Olleta Ltda','name_corto' => 'MCO','item_id5' => '28','tipo_empresa' => 'Soc. de Responsabilidad Limitada','actividad' => 'Venta de Maquinarias para la construcci�n y especialmente art�culos de hidr�ulica','direccion' => 'Recabarren #03350','region_id' => '9','region' => 'Araucania','comuna_id' => '227','comuna' => 'TEMUCO','ciudad_id' => '2','ciudad' => 'Temuco','codpostal' => '0','email' => 'contabilidad@mcoingenieria.cl','fono' => NULL,'feinicio' => '2009-03-15','tipo_tributacion' => 'Art. 14 B','item_id6' => '0','segmento' => 'Grande','item_id10' => '0','codigo' => '475201','giro' => 'VENTA AL POR MENOR DE ART�CULOS DE FERRETER�A Y MATERIALES DE CONSTRUCCI�N&nbsp;','logo' => 'default_logo.jpg','capital' => '0','notario' => NULL,'fenotario' => '2009-08-12','repertorio' => NULL,'nro_edicion' => NULL,'fediario' => '2019-03-18','reg_comercio' => NULL,'notas' => '<p>Rednta AT 2019&nbsp;Devoluci&oacute;n solicitada fue retenida totalmente.</p>','deleted_at' => NULL,'created_at' => '2019-03-18 14:41:51','updated_at' => '2020-03-11 21:10:49'),
            array('id' => '7','rut' => '76025006-6','name' => 'Importadora Massmann Ltda','name_corto' => 'IML','item_id5' => '28','tipo_empresa' => 'Soc. de Responsabilidad Limitada','actividad' => 'Importaci�n, venta de art�culos de Ferreter�a, Maquinaria Herramientas','direccion' => 'Ziem N�2041','region_id' => '9','region' => 'Araucania','comuna_id' => '227','comuna' => 'TEMUCO','ciudad_id' => '2','ciudad' => 'Temuco','codpostal' => '0','email' => 'importadora@importadoramassmann.cl','fono' => NULL,'feinicio' => '2008-07-10','tipo_tributacion' => 'Art. 14 B','item_id6' => '0','segmento' => 'Mediana','item_id10' => '0','codigo' => '466302','giro' => 'VENTA AL POR MAYOR DE MATERIALES DE CONSTRUCCI�N, ART�CULOS DE FERRETER�A, GASFITER�A Y CALEFACCI�N','logo' => 'default_logo.jpg','capital' => '20000000','notario' => NULL,'fenotario' => '2019-03-18','repertorio' => NULL,'nro_edicion' => NULL,'fediario' => '2019-03-18','reg_comercio' => NULL,'notas' => '<p>Renta AT 2019&nbsp; &nbsp; &nbsp;Con pago</p>\\r\\n\\r\\n<p>Declaraci&oacute;n con inconsistencias.</p>\\r\\n\\r\\n<p>Tu declaraci&oacute;n presenta inconsistencias con respecto a la informaci&oacute;n que el SII tiene en sus sistemas y la proporcionada por ti y/o por los agentes retenedores o informantes, por lo tanto se ha impugnado tu declaraci&oacute;n. Para mayor informaci&oacute;n consulte el estado de tu declaraci&oacute;n a partir del 21 de mayo del presente a&ntilde;o.</p>','deleted_at' => NULL,'created_at' => '2019-03-18 17:28:51','updated_at' => '2019-05-16 15:47:06'),
            array('id' => '8','rut' => '76445420-0','name' => 'Sociedad Maketa S.A.','name_corto' => 'Maketa','item_id5' => '29','tipo_empresa' => 'Soc. Anonima','actividad' => 'Fabricaci�n y comercializaci�n de piezas y partes para muebles','direccion' => 'Maestranza #1602','region_id' => '9','region' => 'Araucania','comuna_id' => '227','comuna' => 'TEMUCO','ciudad_id' => '2','ciudad' => 'Temuco','codpostal' => '0','email' => 'rmaldonado@provesur.cl','fono' => NULL,'feinicio' => '2006-01-31','tipo_tributacion' => 'Art. 14 B','item_id6' => '0','segmento' => 'Pequena','item_id10' => '0','codigo' => '162200','giro' => 'FABRICACI�N DE PARTES Y PIEZAS DE CARPINTER�A PARA EDIFICIOS Y CONSTRUCCIONES','logo' => 'default_logo.jpg','capital' => '0','notario' => NULL,'fenotario' => '2019-03-18','repertorio' => NULL,'nro_edicion' => NULL,'fediario' => '2019-03-18','reg_comercio' => NULL,'notas' => '<p>Su devoluci&oacute;n solicitada por $1.954.987 fue autorizada.</p>','deleted_at' => NULL,'created_at' => '2019-03-18 17:37:19','updated_at' => '2020-02-25 14:13:07'),
            array('id' => '9','rut' => '76235345-8','name' => 'Inmobiliaria Intemu Ltda.','name_corto' => 'Intemu','item_id5' => '28','tipo_empresa' => 'Soc. de Responsabilidad Limitada','actividad' => 'Explotaci�n de bienes inmuebles','direccion' => 'ANDRES BELLO #828 DEPTO. #205','region_id' => '9','region' => 'Araucania','comuna_id' => '227','comuna' => 'TEMUCO','ciudad_id' => '2','ciudad' => 'Temuco','codpostal' => '0','email' => 'INGE@FINGER.CL','fono' => NULL,'feinicio' => '2013-01-03','tipo_tributacion' => 'Art. 14 A','item_id6' => '0','segmento' => 'Micro','item_id10' => '0','codigo' => '681012','giro' => 'COMPRA, VENTA Y ALQUILER (EXCEPTO AMOBLADOS) DE INMUEBLES','logo' => 'default_logo.jpg','capital' => '320000000','notario' => NULL,'fenotario' => '2019-03-21','repertorio' => NULL,'nro_edicion' => NULL,'fediario' => '2019-03-21','reg_comercio' => NULL,'notas' => NULL,'deleted_at' => NULL,'created_at' => '2019-03-21 13:40:21','updated_at' => '2019-03-21 13:43:32'),
            array('id' => '10','rut' => '76251733-7','name' => 'Inversiones MW Ltda','name_corto' => 'MW ltda','item_id5' => '28','tipo_empresa' => 'Soc. de Responsabilidad Limitada','actividad' => 'Inversiones y administraci�n de Capitales en general','direccion' => 'Portales #1383','region_id' => '9','region' => 'Araucania','comuna_id' => '227','comuna' => 'TEMUCO','ciudad_id' => '2','ciudad' => 'Temuco','codpostal' => NULL,'email' => 'hmassmann@laolleta.cl','fono' => NULL,'feinicio' => '2013-03-20','tipo_tributacion' => 'Art. 14 A','item_id6' => '0','segmento' => 'Micro','item_id10' => '0','codigo' => '643000','giro' => 'FONDOS Y SOCIEDADES DE INVERSI�N Y ENTIDADES FINANCIERAS SIMILARES','logo' => 'default_logo.jpg','capital' => '5000000','notario' => NULL,'fenotario' => '2019-03-30','repertorio' => NULL,'nro_edicion' => NULL,'fediario' => '2019-03-30','reg_comercio' => NULL,'notas' => NULL,'deleted_at' => NULL,'created_at' => '2019-03-30 10:38:22','updated_at' => '2019-03-30 10:38:22'),
            array('id' => '11','rut' => '77569460-2','name' => 'Inmobiliaria Mawy Ltda.','name_corto' => 'Mawy','item_id5' => '28','tipo_empresa' => 'Soc. de Responsabilidad Limitada','actividad' => 'arrendamiento o alquiler de inmuebles propios o arrendados','direccion' => 'D. Portales 1383','region_id' => '9','region' => 'Araucania','comuna_id' => '227','comuna' => 'TEMUCO','ciudad_id' => '2','ciudad' => 'Temuco','codpostal' => NULL,'email' => 'mwyne@provesur.cl','fono' => '87695505','feinicio' => '2001-03-01','tipo_tributacion' => 'Art. 14 A','item_id6' => '0','segmento' => 'Micro','item_id10' => '0','codigo' => '681012','giro' => 'COMPRA, VENTA Y ALQUILER (EXCEPTO AMOBLADOS) DE INMUEBLES','logo' => 'default_logo.jpg','capital' => '0','notario' => NULL,'fenotario' => '2001-12-19','repertorio' => NULL,'nro_edicion' => NULL,'fediario' => '2019-03-30','reg_comercio' => NULL,'notas' => '<p>Renta AT 2019&nbsp;Declaraci&oacute;n con inconsistencias.</p>','deleted_at' => NULL,'created_at' => '2019-03-30 10:44:45','updated_at' => '2020-02-26 14:12:15'),
            array('id' => '12','rut' => '76046850-9','name' => 'Soc. de Plasticos Carmar Ltda','name_corto' => 'Carmar','item_id5' => '27','tipo_empresa' => 'Persona Natural','actividad' => 'Fabrica de Productos Plasticos','direccion' => 'Botrolhue Hij 282 Lote 15','region_id' => '9','region' => 'Araucania','comuna_id' => '227','comuna' => 'TEMUCO','ciudad_id' => '2','ciudad' => 'Temuco','codpostal' => '12','email' => 'ekogras@gmail.com','fono' => NULL,'feinicio' => '2020-03-13','tipo_tributacion' => 'Renta Presunta','item_id6' => '59','segmento' => 'Personas','item_id10' => '61','codigo' => NULL,'giro' => 'fabrica d','logo' => 'default_logo.jpg','capital' => '0','notario' => NULL,'fenotario' => '2020-03-13','repertorio' => NULL,'nro_edicion' => NULL,'fediario' => '2020-03-13','reg_comercio' => NULL,'notas' => NULL,'deleted_at' => NULL,'created_at' => '2020-03-13 12:47:13','updated_at' => '2020-09-03 11:14:01'),
            array('id' => '13','rut' => '76014397-9','name' => 'Comercial e Industrial Ekogras Ltda.','name_corto' => 'Ekogras','item_id5' => '28','tipo_empresa' => 'Soc. de Responsabilidad Limitada','actividad' => 'Venta al por menor de flores Plantas arboles semillas','direccion' => 'Leon Gallo 1160','region_id' => '9','region' => 'Araucania','comuna_id' => '227','comuna' => 'TEMUCO','ciudad_id' => '2','ciudad' => 'Temuco','codpostal' => NULL,'email' => 'atcortltda@gmail.com','fono' => NULL,'feinicio' => '2020-03-13','tipo_tributacion' => NULL,'item_id6' => '0','segmento' => NULL,'item_id10' => '0','codigo' => NULL,'giro' => NULL,'logo' => 'default_logo.jpg','capital' => '0','notario' => NULL,'fenotario' => '2020-03-13','repertorio' => NULL,'nro_edicion' => NULL,'fediario' => '2020-03-13','reg_comercio' => NULL,'notas' => NULL,'deleted_at' => NULL,'created_at' => '2020-03-13 12:54:05','updated_at' => '2020-03-13 12:54:05'),
            array('id' => '14','rut' => '10718389-2','name' => 'hector berto','name_corto' => 'hbf','item_id5' => '30','tipo_empresa' => 'Soc. Anonima por accion','actividad' => 'actividad empresa','direccion' => 'domicilio','region_id' => '9','region' => 'Araucania','comuna_id' => '227','comuna' => 'TEMUCO','ciudad_id' => '8','ciudad' => 'Pucon','codpostal' => '1234','email' => 'hector@gmail.com','fono' => 'fono','feinicio' => NULL,'tipo_tributacion' => 'Contribuyentes no sujetos al 14 de la LIR','item_id6' => '60','segmento' => 'Pequeñas Empresas','item_id10' => '63','codigo' => '16100','giro' => 'ACTIVIDADES DE APOYO A LA AGRICULTURA','logo' => 'default_logo.jpg','capital' => '0','notario' => 'alarcon','fenotario' => '2020-09-02','repertorio' => NULL,'nro_edicion' => NULL,'fediario' => '2020-09-02','reg_comercio' => NULL,'notas' => NULL,'deleted_at' => NULL,'created_at' => '2020-09-02 10:47:13','updated_at' => '2020-09-02 11:03:00')
        ));
    }
}
